version: '3.7'

services:
  server:
    container_name: tn-ql
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - 4000:4000
    working_dir: /server
    volumes:
      - prisma:/server/src/prisma

volumes:
  prisma:
