name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run linter and formatter
        run: |
          npm run lint
          npm run format

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            git clone https://github.com/abdmmar/tn-ql.git 
            cd tn-ql/
            git pull
            docker-compose up -d --build
            docker image prune -f
            echo 'Deployment success!'
